### ISSUE TITLE
Question about PD confidence intervals

### ISSUE THREAD

**Issue by DeFilippis** [CornellLabofOrnithology/ebirdst#22]
Hello!  Great package.  I was wondering if somebody could explain the procedure you follow to construct the bootstrapped confidence intervals for the partial dependence plots.  Given that PDPs are constructed from grouped data, I didn't think there was a way to construct traditional  confidence bands.  Do you know of any literature that support the method used in this package?

**Comment by tomauer** [comment]
Thanks for your feedback. Daniel Fink, who put those routines together, will reply with details, hopefully in the next 3-4 weeks.

**Comment by df36** [comment]
Hi Evan, 

The partial dependence (PD) estimates we present are ensemble mean estimates, computed as the mean PD estimates based on all of the PD’s estimated from the individual boosted regression tree models (base models) located within a given spatiotemporal region. A straightforward, brute force approach to estimate the uncertainty for the ensemble mean PD can be computed by bootstrapping. However, because fitting the ensemble already entails fitting up to 100 base models, this approach is computationally prohibitive. Instead, we employed a subsampling approach (Politis et al. 2009), creating replicates of the ensemble mean PD by subsampling the individual PDs. To visualize the variation among ensemble mean PD replicates from the subsampling procedure, we fit quantile regressions (using boosted regression trees) and plot the corresponding pointwise confidence region. 

The default parameter value in the code is to subsample 10 individual ensemble PDs to estimate each ensemble mean PD replicate. In many cases, this subsample size is less than the number of PD estimates in the specified spatiotemporal region, resulting in conservative confidence regions. 

If you are interested in subsampling procedures, Geyer (2013) provides a nice discussion and implementation too! 

I hope this helps, 
Daniel Fink

Geyer, C. J. (2013) 5601 Notes: The Subsampling Bootstrap, Available at: http://www.stat.umn.edu/geyer/5601/notes/sub.pdf . Last accessed 06 December 2017.

Politis, D. N., Romano, J.P., and Wolf, M. (1999). Subsampling, Springer Series in Statistics, Springer-Verlag New York, Inc.
