### ISSUE TITLE
calc_bins() fails for Chimney Swift and Purple Martin

### ISSUE THREAD

**Issue by tomauer** [CornellLabofOrnithology/ebirdst#24]
From Lotem at Audubon

The second issue (which I mentioned on the call) is that the calc_bins function sometimes throws an error for me:

 

Error in optim(start, llik, hessian = TRUE, method = method, ...) :

   L-BFGS-B needs finite values of 'fn'

 

This has happened with both Chimney Swift and Purple Martin, and I’m not sure how to fix it. Any ideas?

**Comment by mstrimas** [comment]
As far as I can tell, this only happens when `calc_bins()` is given a RasterStack that only contains zeros or NAs. It's not possible to calculate bins in this case, so I see two options:
1. Return an informative error message.
2. Return NA and maybe a warning.
I'm inclined towards 1 due to the "fail early and often" rule, 2 seems like it'll just push the error further downstream.

**Comment by tomauer** [comment]
Yeah, I think 1 is the best choice.
