### ISSUE TITLE
Clarification of definitions for count and abundance

### ISSUE THREAD

**Issue by conorotompkins** [CornellLabofOrnithology/ebirdst#33]
Hi all, thanks for maintaining this wonderful package. It's a great resource for learning more about the birds I see in my region.

While reading through the documentation and vignettes, I was confused by the definition of `count` vs. `abundance`. I understand that they are both the output of statistical models. `abundance` is "the product of the probability of occurrence and the count conditional on occurrence". So if `occurrence` is 50%, and `count` is 10, `abundance` would be 5. If `occurrence` is 0, `abundance` is 0. Unfortunately I do not understand what `count` is telling me vs. what `abundance` is telling me.

Is there a resource that provides a more colloquial definition of `count` vs. `abundance`?

I have tried to work out some of this own [my blog](https://ctompkins.netlify.app/post/2021-11-23-effect-of-geographic-resolution-on-ebirdst-abundance/). Quick EDA shows that abundance is lower than count, as  I expected based on the definition.
![image](https://user-images.githubusercontent.com/20938344/143076435-0c93f477-6a55-4ba5-8035-f0b755373c5a.png)

**Comment by mstrimas** [comment]
Hi Conor, there's a hurdle style model underlying the relative abundance. First, the "occurrence" (aka encounter rate) is estimated, then within areas where the species is predicted to occur, the expected count is estimated. Relative abundance is then the product of these two values, accounting for both the probability of a species occurring in an area and the number of individuals you'd expect to see in areas where they do occur. I suppose a colloquial definition of count would be the number of individuals a skilled eBirder would expect to see on 1 km/1 hour checklist _conducted within an area where the species occurs_.

This is also an ensemble model with a large number of submodels making up the final raster estimates you see, which is why you'll find that multiplying the count and occurrence rasters doesn't always produce the relative abundance raster; that multiplication is occurring much deeper in the model and there's a bunch of ensemble averaging going on to produce the final rasters.

**Comment by conorotompkins** [comment]
Thanks Matt. I am getting what `count` is now. It also makes sense that I cannot reproduce the output of the ensemble model based on your explanation.

I am still struggling to understand what `abundance` is, and what it provides that `count` does not. If `count` is 5 for an area, and `abundance` is 3, what does that tell me?

**Comment by mstrimas** [comment]
Your initial example was essentially correct, if occurrence is 0.5 (i.e. you have a 50% chance of encountering the species) and count is 10 (i.e. assuming you've encountered the species, you'd see 10 individuals on average), then relative abundance will be 5. One way to think about this is, if you were repeatedly dropped at random locations within the same 3kmx3km grid cell, and conducted a 1km/1h search for the species, relative abundance is the average number of individuals you'd see. However, note that the habitat within the grid cell is heterogenous and sometimes a species just isn't detectable, so on some searches you won't encounter the species at all, occurrence is telling you how often this happens on average.

**Comment by conorotompkins** [comment]
Thanks, this clarifies my understanding! These are the definitions I have in my head now:

- `occurrence` is the probability that I will see the species in an area (not the probability that the species occurs in the area regardless of whether I see it or not). If a bird calls in the forest and no one is there to see it, the `occurrence` is 0.
- `count` is the estimate of how many individuals I expect to see of a species in an area, **if** `occurrence` is > 0
- `abundance` is the average number of individuals I expect to see in an area a priori of knowledge of encounter rate (`occurrence`). If I went to Cape May in September and the encounter rate of CM Warblers is 50%, I may `count` 10 on an individual trip. If I went on 100 trips and the `abundance` is 5, I would expect to see 5 CM Warblers on average.

One project I plan on doing is estimating the "shyest" bird in a given region. My hypothesis is that among woodpeckers, the Pileated Woodpecker would be the most shy in my region. I would define "shy" as which bird has the lowest `occurence` among birds with >0 `occurrence` in the area.

**Comment by mstrimas** [comment]
I think what you have is close, but I'd note that occurrence combines both detection and occupancy, i.e. does the bird occur there and are you likely to encounter it.  It's the detection component that I think you're getting at with shyness, but it would be challenging to estimate with these data because it's confounded with occupancy. A low occurrence species could be very un-shy, but also have low occupancy in a region, e.g. because there is very little habitat. Also, worth noting that all these estimates are made for an "expert" eBirder, someone who's very good at detecting birds, which reduces the impact of detection on occurrence probability, but will never remove it.

**Comment by conorotompkins** [comment]
Thanks Matt, this solidifies my understanding of what data the package provides. Thanks again for maintaining the package!
