### ISSUE TITLE
Function error: calc_full_extent() not working

### ISSUE THREAD

**Issue by sk-moser** [CornellLabofOrnithology/ebirdst#38]
I just started using `ebirdst` for some exploratory data analysis. Not sure if it's a problem on my end or not, but I can't find anything elsewhere on the internet about this so I figured I'd ask here. Everything else so far is working great, but when I try to use `calc_full_extent()` I get the following error:

_Error in calc_full_extent(occ_proj) : could not find function "calc_full_extent"_

And when I run `?ebirdst::calc_full_extent` I get this:

_No documentation for ‘calc_full_extent’ in specified packages and libraries:
you could try ‘??calc_full_extent’_

Seems the function does not exist. Has it been replaced with something different? Thanks!

**Comment by mstrimas** [comment]
This function has been removed, mostly because it was extremely slow. At some point, I intend to transition the R package to use `terra` instead of `raster` in which case I may bring the function back. Did you see the function used in the documentation somewhere?

For now, you can use the pre-calculated full annual extents by calling `load_fac_map_parameters()`.

**Comment by sk-moser** [comment]
Ah, thank you!

I didn't see it in the documentation anywhere, I found it via this tutorial: [https://strimas.com/bioee-4751_ebirdst/](url). Using the pre-calculated full annual extents with `load_fac_map_parameters()` works just fine for me. Thanks again.
